spring.application.name=spring-ecomm

spring.datasource.url=jdbc:mysql://localhost:3306/springecommdb
spring.datasource.username=springeuser
spring.datasource.password=spring@7494

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver